// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import * as dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// Next.js の .env.local を Prisma CLI でも読み込む
dotenv.config({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // db push / migrate には Direct connection を使う（Supabase pooler は非対応）
    url: (process.env["DIRECT_URL"] || process.env["DATABASE_URL"])!,
  },
});
